version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8800:8800"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: inventorymanagement
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

